apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        tamv/jenkins-x-nodejs: true
        tamv/jenkinsx-local: true
        tamv/simple-node-js-react-npm-app: true
        tamv/test-jenkins-x-nodejs: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        tamv/jenkins-x-nodejs: merge
        tamv/jenkinsx-local: merge
        tamv/simple-node-js-react-npm-app: merge
        tamv/test-jenkins-x-nodejs: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - tamv/jenkinsx-local
        - tamv/jenkins-x-nodejs
        - tamv/simple-node-js-react-npm-app
        - tamv/test-jenkins-x-nodejs
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - tamv/jenkinsx-local
        - tamv/jenkins-x-nodejs
        - tamv/simple-node-js-react-npm-app
        - tamv/test-jenkins-x-nodejs
      target_url: http://dashboard-jx.192.168.64.2.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
